### ISSUE TITLE
New term info: Issue with the default template as new items (in same template space) opening in new window

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/geppetto-vfb#280] opened 2018-11-01 16:22 UTC
see https://v2-dev.virtualflybrain.org/org.geppetto.frontend/geppetto?i=VFB_00017894

**Comment by ddelpiano** [comment] 2018-11-01 18:37
@Robbie1977 after analysing this, I can confirm the issue is that the version deployed is not using the latest of the uk.ac.vfb.geppetto bundle from the feature/react_refactoring branch.
The image below can confirm the issue.

![screen shot 2018-11-01 at 19 34 02](https://user-images.githubusercontent.com/37704177/47871763-2e728b80-de0d-11e8-8907-219729ebadbc.png)

From here it's visible that the 1st Collapsible is using data-instancepath, that is because this is created frontend side with the terminfo that fills what required.
Below the second Collapsible is using instancepath, that arrives from the backend.
You need to use the latest of the branch feature/react_refactoring, this is the commit missing at the moment https://github.com/VirtualFlyBrain/uk.ac.vfb.geppetto/commit/d9637d2066ccc78ed92b62e6a926364ab3a416cc .
I let you close this when you are comfortable with it.

**Closed as completed** 2018-11-01 21:26 UTC
Labels: invalid, wontfix
